### ISSUE TITLE
Feature request: Indirect torch hits don't consume torches

### ISSUE THREAD

**Issue by tesseract-two** [Nyphet/torch-hit#11]
A configuration option to not consume torches on indirect hit, regardless of the consumeTorch value.

Because lighting your sword on fire and then hitting something with the sword wouldn't break the torch, right?

**Comment by Crystal-Spider** [comment]
Makes sense, I will work on this as soon as I can. Probably I will add a configuration option for this, defaulting to not consuming with indirect hits.  
Thanks for the suggestion.

**Comment by Crystal-Spider** [comment]
This feature is now available with v6.0.1.0

**Comment by tesseract-two** [comment]
Thank you!
