### ISSUE TITLE
Config option "indirect-tools" keeps being overriden

### ISSUE THREAD

**Issue by JohnSmith474** [Nyphet/torch-hit#12]
**Describe the bug**
The config option "indirect-tools" reverts back to standard when left empty.

**To Reproduce**
1. Replace line 10 in the config file ""indirect tools" = ["sword", "axe", "pickaxe", "shovel", "hoe"]" with ""indirect tools" = []".
2. After restarting the game it will revert back to ""indirect tools" = ["sword", "axe", "pickaxe", "shovel", "hoe"]".

**Expected behavior**
It should stay as ""indirect tools" = []"

**Screenshots**
Not applicable

**Stacktrace and logs**
[12Jan.2023 02:12:22.714] [modloading-worker-0/WARN] [net.minecraftforge.common.ForgeConfigSpec/CORE]: Configuration file ...\config\torchhit-common.toml is not correct. Correcting

**System information:**
Forge 1.18.2 40.1.93
Torch Hit 1.18.2 6.0.1.0
Minecraft 1.18.2

**Additional context**
The option does work properly when editing the config with a config manager like Configured. However, this lasts only until the game is restarted.

**Comment by Crystal-Spider** [comment]
I could replicate the issue, it also happens for the other array-like configuration options.

**Comment by Crystal-Spider** [comment]
I found out what was causing the issue, I will release the fix as soon as I can.

**Comment by Crystal-Spider** [comment]
Fixed with version v6.0.1.1
