### ISSUE TITLE
Upload on Modrinth Please

### ISSUE THREAD

**Issue by sternschnaube** [Nyphet/torch-hit#13]
https://modrinth.com/

Hello, great mod - would be nicee to use the popularity from Modrinth to show this mod a bigger audience 🥳

**Comment by Crystal-Spider** [comment]
It seems like a good idea. I have a couple of fixes and improvements for this mod (and others).  
When everything will be ready, and also I'll have some more free time, I will definitely consider publishing on Modrinth.

**Comment by sternschnaube** [comment]
Great to hear 😊

**Comment by Crystal-Spider** [comment]
Starting from version v6.0.1.1 Torch Hit! will be available on Modrinth
