### ISSUE TITLE
Additional features

### ISSUE THREAD

**Issue by sternschnaube** [Nyphet/torch-hit#14]
Hello, the last days I was stepping on this wonderful mod.
I see better chances for a revive as integration with your mod - maybe you like the idea 😊

Look here please for more:
https://github.com/OnyxStudios/Realistic-Cobwebs/issues/3

https://www.curseforge.com/minecraft/mc-mods/realistic-cobwebs

**Comment by Crystal-Spider** [comment]
This would go beyond the scope of this mod, but if the original author won't update that mod I can tell you that I'll create myself a new mod to revive it!  
Thanks for the suggestion

**Comment by sternschnaube** [comment]
Awesome to hear 🥳
