### ISSUE TITLE
Unable to edit and save the configuration file normally.

### ISSUE THREAD

**Issue by KeVrX** [Nyphet/torch-hit#15]
**Describe the bug**
After editing the configuration file, reloading the game will make it overwritten.

**To Reproduce**
1.Edit the "extra torch items" list with adding a new item.
2.Save the configuration file **successfully**. (Sometimes you cannot save it successfully.)
3.Reload after exiting the game.

**Expected behavior**
The edited content should be saved and take effect normally in the game.

**System information:**
 - Forge 43.2.0
 - 6.0.1.0
 - 1.19.2

**Additional context**
Sometimes the configuration file cannot be saved successfully after editing, but a .bak file will be generated.

**Comment by Crystal-Spider** [comment]
Same problem as #12  
Will fix is as soon as I have enough free time

**Comment by Crystal-Spider** [comment]
I'm working on it, please follow the other issue for updates. In a few days I should be releasing a new version with the fix.
