### ISSUE TITLE
Update to 1.20.1 Please

### ISSUE THREAD

**Issue by sternschnaube** [Nyphet/torch-hit#18]

**Comment by Crystal-Spider** [comment]
Hi, don't worry, it will happen soon!  
I'm currently in the midst of getting my degree in Computer Science, so I'm very busy, but you can expect the port to come by July!

I will close this issue when I port to 1.20.1, so that you and anyone else following the issue can receive a precise update.

**Comment by sternschnaube** [comment]
Good to hear, take your time please - thanks 🥳
