### ISSUE TITLE
Is Soul Fire'd required?

### ISSUE THREAD

**Issue by tesseract-two** [Nyphet/torch-hit#19]
**Question**
Is Soul Fire's required?

**Additional context**
The docker image I'm using to run my server auto-downloads required dependencies; however, I'm only running server side mods for Geyser/Bedrock compatibility. If Soul Fire's isn't required would you mind marking it as a optional dependency on Modrinth? (Including the 1.20.1 builds?)

**Comment by Crystal-Spider** [comment]
Nope, it's not required. That's weird, in Modrinth it should already be listed as optional dependency, I'll check this out asap.

**Comment by tesseract-two** [comment]
Thanks!

**Comment by Crystal-Spider** [comment]
It should be fixed now, let me know!

**Comment by tesseract-two** [comment]
Yup, thank you!
