### ISSUE TITLE
Players can set other players on fire even with pvp disabled

### ISSUE THREAD

**Issue by HatTrkPatrk** [Nyphet/torch-hit#21]
**Describe the bug**
With this mod installed, and with pvp=false set in server.properties, players can still set other players on fire by attacking them with a torch, dealing damage to them (indirectly?).

**To Reproduce**
Install this torchhit mod
Disable pvp on server
Hold a torch and smack another player with it

**Expected behavior**
Player does not get set on fire because pvp is disabled

**System information:**
 - Mod loader (Fabric or Forge): Fabric
 - Mod version: 6.0.1.2
 - Minecraft version: 1.20.2

**Comment by Crystal-Spider** [comment]
You're absolutely right, going to fix it soon!
