### ISSUE TITLE
Feature request: Option to enable hitting creeper with torch to ignite them

### ISSUE THREAD

**Issue by 3ncanis** [Nyphet/torch-hit#22]
Basically I think it would be a cool feature where hitting a creeper with a torch causes it to ignite similar to how right clicking on them with a flint and steel works.

**Comment by Crystal-Spider** [comment]
Duplicate of #7 

Does fire aspect set creepers on fire?

**Comment by 3ncanis** [comment]
Yes?

**Comment by Crystal-Spider** [comment]
Sorry, I meant, does fire aspect ignite creepers and make them explode? Or does it only set them on fire?  
Torches are meant to be an early game alternative to fire aspect, or a way to get a combat advantage by not using the shield in caves, so the behavior should be consistent with that.

**Comment by 3ncanis** [comment]
Understandable, just thought it would be a fun feature you could toggle on, disabled by default. But I do realize it would pretty much make flint and steel useless
