### ISSUE TITLE
Compatibility Request: Torch hit! Mod with Soul Fire'd Mod

### ISSUE THREAD

**Issue by YuJianghan** [Nyphet/torch-hit#25]
### I have confirmed no other issue asks for this

- [X] I have searched for existing issues

### Other mod

Soul Fire'd

### Current behavior

When using a soul torch to attack mobs with Torch hit! mod enabled, the following issues occur:
- Mobs catch standard orange fire instead of blue soul fire.
- Attacking Piglins with a soul torch results in fire that lasts twice as long as normal.

Despite this, Soul Fire'd mod effects work independently:
- Soul fire burns with a blue flame.
- Arrows passing through soul fire ignite with blue flame.

### Desired behavior

When using a soul torch to attack mobs with Torch hit! mod enabled, the Soul Fire'd mod effects should apply:
- Mobs should catch blue soul fire instead of standard fire.
- Fire duration on Piglins should match the intended duration for soul fire.

### Stacktrace and logs

No crashes occur. The issue is with the behavior of fire effects when using soul torches. 

### Additional context

**Minecraft Version**: 1.20.4_Fabric_0.15.11  
**Mod List**:
- `fabric-api-0.97.1+1.20.4`
- `ForgeConfigAPIPort-v20.4.3-1.20.4-Fabric`
- `torchhit-1.20.4-6.0.2.0-fabric`
- `soul-fire-d-fabric-1.20.4-4.0.2`
- `cobweb-fabric-1.20.4-1.0.0`

https://github.com/Crystal-Nest/torch-hit/assets/58395036/3b146b70-a83c-4310-8041-1f124176c4ed

**Comment by Crystal-Spider** [comment]
It's normal, I need to update this mod.  
In the meantime, you can downgrade SF to 3.2.0.x

**Comment by YuJianghan** [comment]
Thank you for your quick response!

**Comment by Crystal-Spider** [comment]
Fixed with [v7.0.0](https://github.com/crystal-nest/torch-hit/releases?q=7.0.0).
