### ISSUE TITLE
Version 7.0.0 Isn’t Compatible with 1.21.1 Versions of Forge Config API Port

### ISSUE THREAD

**Issue by LordOfTheWeebs** [Nyphet/torch-hit#27]
### I have confirmed no other issue reports this bug

- [X] I have searched for existing issues

### I have confirmed the mod is installed on the proper side

- [X] I have installed the mod properly

### Current behavior

Upon attempting to load an instance with Torch Hit, the game crashes and says that Torch Hit requires Forge Config API Port versions 21.0.1 (inclusive) and 21.1- (exclusive) while using Forge Config API Port version 21.1.1 (also 21.1.0, the only two available versions for Minecraft 1.21.1)

### Expected behavior

The game to run as normal with the mods installed.

### Steps to reproduce

1. Place Torch Hit and its dependencies, specifically either version 21.1.0 or 21.1.1 of Forge Config API Port, in the mods folder and run.

### Minecraft version

1.21.1

### Mod loader version

0.16.9

### Mod version

7.0.0

### Other mods

Fabric API version 0.107.0
Cobweb version 1.1.3
Forge Config API Port version 21.1.1 or 21.1.0

### Stacktrace and logs

https://pastebin.com/Em35EZm6

### Additional context

Given that 21.1.0 and 21.1.1 are the only "21.1" versions of Forge Config API Port, neither seem to work with Torch Hit, and given that version 21.0.1 of Forge Config API Port doesn't work with 1.21.1, version 7.0.0 of Torch Hit can't run on 1.21.1 and shouldn't be labeled as such on the Modrinth or CurseForge pages.

**Comment by Crystal-Spider** [comment]
Sorry for the inconvenience, I updated the version.  
Try downloading the mod again, it should be fixed now.
