### ISSUE TITLE
1.19.3 (Fabric)

### ISSUE THREAD

**Issue by AstromanGaming** [Nyphet/torch-hit#9]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
N/A

**Describe alternatives you've considered**
N/A

**Additional context**
Hello, can you update your mod to 1.19.3? Because it is not compatible.

**Comment by Crystal-Spider** [comment]
I will as soon as Forge releases a stable version of their API for 1.19.3.

**Comment by AstromanGaming** [comment]
Ok but I'm talking about Fabric. (Sorry for the confusion.)

**Comment by Crystal-Spider** [comment]
This is valid also for Fabric because I need to keep my workflow organized and I will release both versions after a while, to ensure stability in both APIs.
